[tool:pytest]
markers =
    smoke: critical tests
    regression: full test suite
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --headed
    --html=reports/report.html
    --self-contained-html
    -s
